### ISSUE TITLE
SALWYRR LAUNCHER compatibility?

### ISSUE THREAD

**Issue by Klover91** [PluginBugs/Issues-CosmeticsCore#101]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Kloverfist#6198

### What happened?

With Salwyrr launcher (https://www.salwyrr.com/) everytime i get into the wardrobe i can't see the gui correctly.

### Steps to reproduce the issue

1.open salwyrr
2.enter the wardrobe

### Server version

1.19.2

### CosmeticsCore Version

1.2.0

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.23

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/114626224/220178555-aee35b35-ea20-4023-a4fa-10700f715f47.png)

**Comment by LoneDev6** [comment]
Check your CLIENT log(not server).
It is usually located here: `%appdata%\.minecraft\logs\latest.log`

Anyway there is nothing I can do since I'm not the developer of that launcher and I have no idea of which trickery they are doing under the hood, it's most likely a bug of their launcher and you might be able to read some errors in the log file.

**Comment by Klover91** [comment]
ok thank you very much, i'll try to connect with them later. peace
