### ISSUE TITLE
Helmets deleted when switching from Creative to Survival

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [PluginBugs/Issues-CosmeticsCore#16]
### What happened?

Disclaimer: although terms are agree, I don't see this bug mentioned in Polymart's update logs (https://polymart.org/resource/cosmeticscore-launch-discount.2879/updates).

Swapping gamemodes from Creative to Survival with a helmet equipped deletes it (not unequip). So far, it's consistently deleted Diamond Helmets and only sometimes deleting Leather Helmets.

This behaviour stopped when CosmeticCore was disabled.

### Steps to reproduce the issue

1. Install CosmeticsCore
2. Join the game and equip a Diamond Helmet (untested other helmets)
3. Swap into Creative mode with Helmet equipped
4. Swap back to Survival mode and see that the Helmet is gone.

### Server version

This server is running Paper version git-Paper-138 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

### CosmeticsCore Version

CosmeticsCore version 1.0.0-beta1

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.21

**Comment by LoneDev6** [comment]
It's a normal behavior because the client has a bug in creative mode, I don't think there is a solution for that.

**Comment by ProfessionalBoatDrifter** [comment]
> It's a normal behavior because the client has a bug in creative mode, I don't think there is a solution for that.

Sorry, I don't understand. How is this normal client behaviour when it's only happening when CosmeticsCore is running?

**Comment by LoneDev6** [comment]
> Sorry, I don't understand. How is this normal client behaviour when it's only happening when CosmeticsCore is running?

Gamemode CREATIVE is a special gamemode with which the client is allowed to do ANYTHING, the server basically stops any check to the player inventory.
Cosmetics core uses packet based item to create hats, so that it won't overwrite the real helmet on head.

When in CREATIVE gamemode the client will automatically think that the fake packet based item is the real item in the inventory, so it overwrites the real helmet.

The issue is that the cosmetic is overwriting the real helmet when the player switches from SURVIVAL to CREATIVE.

The only solution I had in mind was to basically remove the helmet completely when changing back to SURVIVAL to avoid players from keeping the cosmetic in the survival gameplay.

Do you have any other solution to handle that?
I might just disallow hat cosmetics in CREATIVE completely.

**Comment by LoneDev6** [comment]
I'll try to find a better solution, for now this was the only straight forward solution

**Comment by BrandonT80** [comment]
Randomly players helmets are being deleted. Most players report having used the fox hat, but some did not have any cosmetics in use. None of them have access to creative. Not sure if this helps any, but might be good to know.

**Comment by BrandonT80** [comment]
> 

Could a config option be made for us to enable creative mode cosmetics? Or is that not good with the plugins structure overall?

**Comment by BrandonT80** [comment]
> > Sorry, I don't understand. How is this normal client behaviour when it's only happening when CosmeticsCore is running?
> 
> [**REDACTED**]
> 
> The only solution I had in mind was to basically remove the helmet completely when changing back to SURVIVAL to avoid players from keeping the cosmetic in the survival gameplay.
> 
> Do you have any other solution to handle that? I might just disallow hat cosmetics in CREATIVE completely.

Could a config option be made for us to enable creative mode cosmetics? Or is that not good with the plugins structure overall?

**Comment by BrandonT80** [comment]
Is there any update on this? This is the only reason I don't use the plugin right now is that it deletes helmets constantly. Ex: World changes that change the gamemode will cause deletions.

**Comment by LoneDev6** [comment]
I didn't find any proper solution for now because of how this stupid game works.
I'll try again to see if I can come up with something clean to fix that issue.

**Comment by Akiranya** [comment]
As far as I can tell, it's usually just the OP who can switch gamemodes, in which this bug could be neglected. Or the servers which allow players to swtich gamemodes (like a creative server, which is much less common compared to a normal survival server I guess?)

I know the game uses different network protocol for survival and gamemode and it makes tricky code to be more tricky. And If this bug were to be tricky to fix, I just hope the fix wouldn't affect the most servers where players are in all survival mode at all times (like performance dropping caused by the fix). I'm also a developer and knows how this stupid game works and aware of that it usually takes more time & costs more performance if I were to fix/create something that wouldn't have existed in the game base. Examples include the custom entities and emotes (which heavily use armor stands and usually cost a lot more network bandwidth compared to that if it were officially supported by mojang)

**Comment by LoneDev6** [comment]
> if I were to fix/create something that wouldn't have existed in the game base.

I wish it was just that, if it was a performance issue I'd just have coded it anyway and put a warning and made it toggleable, but the issue is that this feature is actually tricky to achieve.
I'll try again to see if I can come up with an hacky way to bypass this issue, but it's not really easy to do.
