### ISSUE TITLE
Request more API

### ISSUE THREAD

**Issue by hoanght2512** [PluginBugs/Issues-CosmeticsCore#162]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

hothienhoang

### Describe the solution you'd like

make more API to:
- Get type for cosmetic
- Get cosmetic list player has permission to using
- Permissions for limit equip (Ex: Vip access 2 cosmetics in body)
- method for equip, unequip (including limit)
- Event when player enter arena (including cancel open GUI)

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

I while try coding plugin cosmetics for Bedrock

**Comment by LoneDev6** [comment]
> Get type for cosmetic

Already requested: https://github.com/PluginBugs/Issues-CosmeticsCore/issues/136

> Permissions for limit equip (Ex: Vip access 2 cosmetics in body)

This is not an API request, correct? You're requesting a new permission to allow customization of the limit per-player, right?

 > method for equip, unequip (including limit)

These methods already exist.
Are you requesting these methods to take limit into account instead of bypassing it?

> Event when player enter arena (including cancel open GUI)

There is already an event of when the player opens the wardrobe
